#!/usr/bin/env ruby


libs = []
libs << "irb/completion"
libs << File.dirname(__FILE__) + '/lib/tw_utilization'

command_line = []
command_line << "irb"
command_line << libs.inject("") { |acc, lib| acc + %( -r "#{lib}") }
command_line << "--simple-prompt"
command = command_line.join(" ")

exec command
